# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu-16.04'
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- script: 'tsc && node ./bin/index.js --clone --onlyTestTsNext'
  displayName: 'node ./bin/index.js --clone --onlyTestTsNext'

trigger:
- master


